<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>com.sample.advancedrecyclerview</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MvvmCross" Version="10.1.2" />
    <PackageReference Include="MvvmCross.DroidX.RecyclerView" Version="10.1.2" />
    <PackageReference Include="MvvmCross.Plugin.Color" Version="10.1.2" />
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.12.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MvvmCross-Support\MvvmCross.AdvancedRecyclerView.csproj" />
    <ProjectReference Include="..\Sample.Core\Sample.Core.csproj" />
  </ItemGroup>

</Project>
